// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6jwFAGLk0FC7X38lVNO8V5pjrkGs_X_Y',
    appId: '1:959472019023:web:2e0ca22836645bab37ec3a',
    messagingSenderId: '959472019023',
    projectId: 'test-e42b9',
    authDomain: 'test-e42b9.firebaseapp.com',
    storageBucket: 'test-e42b9.appspot.com',
    measurementId: 'G-SB5QCRSDDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJ_ZJGudri48xYP-RwuXc75u_vt_UF94',
    appId: '1:959472019023:android:597556152d5c08a337ec3a',
    messagingSenderId: '959472019023',
    projectId: 'test-e42b9',
    storageBucket: 'test-e42b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTCqpxFKOmgRfztp0Jl7dKbyi--pQ6gog',
    appId: '1:959472019023:ios:d0b4d1cc9f80ea1c37ec3a',
    messagingSenderId: '959472019023',
    projectId: 'test-e42b9',
    storageBucket: 'test-e42b9.appspot.com',
    iosClientId: '959472019023-4dpjcuj9b3o3ss5uhru45qck0bs59grp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTCqpxFKOmgRfztp0Jl7dKbyi--pQ6gog',
    appId: '1:959472019023:ios:d0b4d1cc9f80ea1c37ec3a',
    messagingSenderId: '959472019023',
    projectId: 'test-e42b9',
    storageBucket: 'test-e42b9.appspot.com',
    iosClientId: '959472019023-4dpjcuj9b3o3ss5uhru45qck0bs59grp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
